DATAPATH_MCDMA_HIER_DATAPATH_MCDMA_0_axi_mcdma_0:
- axi_mcdma
- mcdma
DATAPATH_MCDMA_HIER_DATAPATH_MCDMA_1_axi_mcdma_0:
- axi_mcdma
- mcdma
DATAPATH_MCDMA_HIER_DATAPATH_MCDMA_2_axi_mcdma_0:
- axi_mcdma
- mcdma
DATAPATH_MCDMA_HIER_DATAPATH_MCDMA_3_axi_mcdma_0:
- axi_mcdma
- mcdma
DATAPATH_MCDMA_HIER_axi_gpio_0:
- axi_gpio
- gpio
GT_WRAPPER_axi_gpio_gt_rate_reset_ctl_0:
- axi_gpio
- gpio
GT_WRAPPER_axi_gpio_gt_rate_reset_ctl_1:
- axi_gpio
- gpio
GT_WRAPPER_axi_gpio_gt_rate_reset_ctl_2:
- axi_gpio
- gpio
GT_WRAPPER_axi_gpio_gt_rate_reset_ctl_3:
- axi_gpio
- gpio
GT_WRAPPER_axi_gpio_gt_reset_mask:
- axi_gpio
- gpio
GT_WRAPPER_gt_quad_base:
- gt_quad_base
- None
MRMAC_1588_HELPER_HIER_SYS_TIMER_0_ptp_1588_timer_syncer_0:
- ptp_1588_timer_syncer
- None
MRMAC_1588_HELPER_HIER_SYS_TIMER_1_ptp_1588_timer_syncer_0:
- ptp_1588_timer_syncer
- None
MRMAC_1588_HELPER_HIER_SYS_TIMER_2_ptp_1588_timer_syncer_0:
- ptp_1588_timer_syncer
- None
MRMAC_1588_HELPER_HIER_SYS_TIMER_3_ptp_1588_timer_syncer_0:
- ptp_1588_timer_syncer
- None
mrmac_0_core:
- mrmac
- None
versal_cips_0_pspmc_0_psv_adma_0:
- psv_adma
- zdma
versal_cips_0_pspmc_0_psv_adma_1:
- psv_adma
- zdma
versal_cips_0_pspmc_0_psv_adma_2:
- psv_adma
- zdma
versal_cips_0_pspmc_0_psv_adma_3:
- psv_adma
- zdma
versal_cips_0_pspmc_0_psv_adma_4:
- psv_adma
- zdma
versal_cips_0_pspmc_0_psv_adma_5:
- psv_adma
- zdma
versal_cips_0_pspmc_0_psv_adma_6:
- psv_adma
- zdma
versal_cips_0_pspmc_0_psv_adma_7:
- psv_adma
- zdma
versal_cips_0_pspmc_0_psv_canfd_1:
- psv_canfd
- canfd
versal_cips_0_pspmc_0_psv_coresight_a720_cti:
- psv_coresight_a720_cti
- None
versal_cips_0_pspmc_0_psv_coresight_a720_dbg:
- psv_coresight_a720_dbg
- None
versal_cips_0_pspmc_0_psv_coresight_a720_etm:
- psv_coresight_a720_etm
- None
versal_cips_0_pspmc_0_psv_coresight_a720_pmu:
- psv_coresight_a720_pmu
- None
versal_cips_0_pspmc_0_psv_coresight_a721_cti:
- psv_coresight_a721_cti
- None
versal_cips_0_pspmc_0_psv_coresight_a721_dbg:
- psv_coresight_a721_dbg
- None
versal_cips_0_pspmc_0_psv_coresight_a721_etm:
- psv_coresight_a721_etm
- None
versal_cips_0_pspmc_0_psv_coresight_a721_pmu:
- psv_coresight_a721_pmu
- None
versal_cips_0_pspmc_0_psv_coresight_apu_cti:
- psv_coresight_apu_cti
- None
versal_cips_0_pspmc_0_psv_coresight_apu_ela:
- psv_coresight_apu_ela
- None
versal_cips_0_pspmc_0_psv_coresight_apu_etf:
- psv_coresight_apu_etf
- None
versal_cips_0_pspmc_0_psv_coresight_apu_fun:
- psv_coresight_apu_fun
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_atm:
- psv_coresight_cpm_atm
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_cti2a:
- psv_coresight_cpm_cti2a
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_cti2d:
- psv_coresight_cpm_cti2d
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_ela2a:
- psv_coresight_cpm_ela2a
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_ela2b:
- psv_coresight_cpm_ela2b
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_ela2c:
- psv_coresight_cpm_ela2c
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_ela2d:
- psv_coresight_cpm_ela2d
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_fun:
- psv_coresight_cpm_fun
- None
versal_cips_0_pspmc_0_psv_coresight_cpm_rom:
- psv_coresight_cpm_rom
- None
versal_cips_0_pspmc_0_psv_coresight_fpd_atm:
- psv_coresight_fpd_atm
- None
versal_cips_0_pspmc_0_psv_coresight_fpd_cti1b:
- psv_coresight_fpd_cti1b
- None
versal_cips_0_pspmc_0_psv_coresight_fpd_cti1c:
- psv_coresight_fpd_cti1c
- None
versal_cips_0_pspmc_0_psv_coresight_fpd_cti1d:
- psv_coresight_fpd_cti1d
- None
versal_cips_0_pspmc_0_psv_coresight_fpd_stm:
- psv_coresight_fpd_stm
- None
versal_cips_0_pspmc_0_psv_coresight_lpd_atm:
- psv_coresight_lpd_atm
- None
versal_cips_0_pspmc_0_psv_coresight_lpd_cti:
- psv_coresight_lpd_cti
- None
versal_cips_0_pspmc_0_psv_coresight_pmc_cti:
- psv_coresight_pmc_cti
- None
versal_cips_0_pspmc_0_psv_coresight_r50_cti:
- psv_coresight_r50_cti
- None
versal_cips_0_pspmc_0_psv_coresight_r51_cti:
- psv_coresight_r51_cti
- None
versal_cips_0_pspmc_0_psv_crf_0:
- psv_crf
- None
versal_cips_0_pspmc_0_psv_crl_0:
- psv_crl
- None
versal_cips_0_pspmc_0_psv_crp_0:
- psv_crp
- None
versal_cips_0_pspmc_0_psv_ethernet_0:
- psv_ethernet
- emacps
versal_cips_0_pspmc_0_psv_ethernet_1:
- psv_ethernet
- emacps
versal_cips_0_pspmc_0_psv_fpd_afi_0:
- psv_fpd_afi
- None
versal_cips_0_pspmc_0_psv_fpd_afi_2:
- psv_fpd_afi
- None
versal_cips_0_pspmc_0_psv_fpd_cci_0:
- psv_fpd_cci
- None
versal_cips_0_pspmc_0_psv_fpd_gpv_0:
- psv_fpd_gpv
- None
versal_cips_0_pspmc_0_psv_fpd_maincci_0:
- psv_fpd_maincci
- None
versal_cips_0_pspmc_0_psv_fpd_slave_xmpu_0:
- psv_fpd_slave_xmpu
- None
versal_cips_0_pspmc_0_psv_fpd_slcr_0:
- psv_fpd_slcr
- None
versal_cips_0_pspmc_0_psv_fpd_slcr_secure_0:
- psv_fpd_slcr_secure
- None
versal_cips_0_pspmc_0_psv_fpd_smmu_0:
- psv_fpd_smmu
- None
versal_cips_0_pspmc_0_psv_fpd_smmutcu_0:
- psv_fpd_smmutcu
- None
versal_cips_0_pspmc_0_psv_i2c_0:
- psv_i2c
- iicps
versal_cips_0_pspmc_0_psv_i2c_1:
- psv_i2c
- iicps
versal_cips_0_pspmc_0_psv_ipi_psm:
- psv_ipi
- ipipsu
versal_cips_0_pspmc_0_psv_lpd_afi_0:
- psv_lpd_afi
- None
versal_cips_0_pspmc_0_psv_lpd_iou_secure_slcr_0:
- psv_lpd_iou_secure_slcr
- None
versal_cips_0_pspmc_0_psv_lpd_iou_slcr_0:
- psv_lpd_iou_slcr
- None
versal_cips_0_pspmc_0_psv_lpd_slcr_0:
- psv_lpd_slcr
- None
versal_cips_0_pspmc_0_psv_lpd_slcr_secure_0:
- psv_lpd_slcr_secure
- None
versal_cips_0_pspmc_0_psv_lpd_xppu_0:
- psv_lpd_xppu
- None
versal_cips_0_pspmc_0_psv_ocm_ctrl:
- psv_ocm
- None
versal_cips_0_pspmc_0_psv_ocm_xmpu_0:
- psv_ocm_xmpu
- None
versal_cips_0_pspmc_0_psv_pmc_aes:
- psv_pmc_aes
- None
versal_cips_0_pspmc_0_psv_pmc_bbram_ctrl:
- psv_pmc_bbram_ctrl
- None
versal_cips_0_pspmc_0_psv_pmc_cfi_cframe_0:
- psv_pmc_cfi_cframe
- cframe
versal_cips_0_pspmc_0_psv_pmc_cfu_apb_0:
- psv_pmc_cfu_apb
- cfupmc
versal_cips_0_pspmc_0_psv_pmc_dma_0:
- psv_pmc_dma
- csudma
versal_cips_0_pspmc_0_psv_pmc_dma_1:
- psv_pmc_dma
- csudma
versal_cips_0_pspmc_0_psv_pmc_efuse_cache:
- psv_pmc_efuse_cache
- None
versal_cips_0_pspmc_0_psv_pmc_efuse_ctrl:
- psv_pmc_efuse_ctrl
- None
versal_cips_0_pspmc_0_psv_pmc_global_0:
- psv_pmc_global
- None
versal_cips_0_pspmc_0_psv_pmc_gpio_0:
- psv_pmc_gpio
- gpiops
versal_cips_0_pspmc_0_psv_pmc_ppu1_mdm_0:
- psv_pmc_ppu1_mdm
- uartlite
versal_cips_0_pspmc_0_psv_pmc_qspi_0:
- psv_pmc_qspi
- qspipsu
versal_cips_0_pspmc_0_psv_pmc_ram_npi:
- psv_pmc_ram_npi
- None
versal_cips_0_pspmc_0_psv_pmc_rsa:
- psv_pmc_rsa
- None
versal_cips_0_pspmc_0_psv_pmc_rtc_0:
- psv_pmc_rtc
- rtcpsu
versal_cips_0_pspmc_0_psv_pmc_sd_1:
- psv_pmc_sd
- sdps
versal_cips_0_pspmc_0_psv_pmc_sha:
- psv_pmc_sha
- None
versal_cips_0_pspmc_0_psv_pmc_slave_boot:
- psv_pmc_slave_boot
- None
versal_cips_0_pspmc_0_psv_pmc_slave_boot_stream:
- psv_pmc_slave_boot_stream
- None
versal_cips_0_pspmc_0_psv_pmc_sysmon_0:
- psv_pmc_sysmon
- sysmonpsv
versal_cips_0_pspmc_0_psv_pmc_trng:
- psv_pmc_trng
- trngpsv
versal_cips_0_pspmc_0_psv_pmc_xmpu_0:
- psv_pmc_xmpu
- None
versal_cips_0_pspmc_0_psv_pmc_xppu_0:
- psv_pmc_xppu
- None
versal_cips_0_pspmc_0_psv_pmc_xppu_npi_0:
- psv_pmc_xppu_npi
- None
versal_cips_0_pspmc_0_psv_psm_global_reg:
- psv_psm_global_reg
- None
versal_cips_0_pspmc_0_psv_psm_iomodule_0:
- iomodule
- iomodule
versal_cips_0_pspmc_0_psv_psm_ram_data_cntlr:
- PSM_PPU
- None
versal_cips_0_pspmc_0_psv_psm_ram_instr_cntlr:
- ram_instr_cntlr
- None
versal_cips_0_pspmc_0_psv_psm_tmr_inject_0:
- tmr_inject
- tmr_inject
versal_cips_0_pspmc_0_psv_psm_tmr_manager_0:
- tmr_manager
- tmr_manager
versal_cips_0_pspmc_0_psv_r5_0_atcm_global:
- psv_tcm_global
- None
versal_cips_0_pspmc_0_psv_r5_1_atcm_global:
- psv_tcm_global
- None
versal_cips_0_pspmc_0_psv_r5_1_btcm_global:
- psv_tcm_global
- None
versal_cips_0_pspmc_0_psv_sbsauart_0:
- psv_sbsauart
- uartpsv
versal_cips_0_pspmc_0_psv_scntr_0:
- psv_scntr
- None
versal_cips_0_pspmc_0_psv_scntrs_0:
- psv_scntrs
- None
versal_cips_0_pspmc_0_psv_usb_0:
- psv_usb
- None
versal_cips_0_pspmc_0_psv_usb_xhci_0:
- psv_usb_xhci
- usbpsu
